#pragma once

#include "core/event.h"
#include "platform/window.h"

#include <cstdint>
#include <memory>
#include <string>
#include <vector>


class Renderer;
class AssetManager;


// this is the main class of the project, it combines the rendering and window logic
class Application
{
public:
    Application(uint32_t width, uint32_t height, const std::string& title);
    virtual ~Application();

    Application(const Application&) = delete;
    Application& operator=(const Application&) = delete;
    Application(Application&&) = delete;
    Application& operator=(Application&&) = delete;

    // the main engine method
    void run();

protected:
    // methods to be implemented by the Sandbox apps
    // render features have their own onRender
    virtual void onInit() {}

    virtual void onTick(float deltaTime) {}
    virtual void onImgui() {}
    virtual void onShutdown() {}

    // call destructors in reverse order, important ordering for now
    Window m_window;
    std::unique_ptr<Renderer> m_renderer;
    std::unique_ptr<AssetManager> m_assetManager;

private:
    // processes events generated by app
    void processEvents();

    // TODO: move to seperate file that handles inputs?
    void processInputs();

    // methods that streamline apps logic
    void tickLogic(float deltaTime);
    void tickRender(float deltaTime);

    // stores events then handles them in order
    std::vector<Event> m_eventQueue;

    bool m_isRunning{false};
    bool m_isMinimized{false};
};